//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayVideoInMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubtitleStyle
    {
        public int StyleId { get; set; }
        public string StyleName { get; set; }
        public int FontId { get; set; }
        public int FontSize { get; set; }
        public string FontColor { get; set; }
        public string BorderColor { get; set; }
        public int BorderWidth { get; set; }
        public string ShadowColor { get; set; }
        public int ShadowX { get; set; }
        public int ShadowY { get; set; }
        public int TabSize { get; set; }
        public int LineSpace { get; set; }
        public int MarginH { get; set; }
        public int MarginV { get; set; }
        public int Align { get; set; }
    
        public virtual FontDefine FontDefine { get; set; }
    }
}
