//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayVideoInMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HDDelay5Entities : DbContext
    {
        public HDDelay5Entities()
            : base("name=HDDelay5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<RecordLowre> RecordLowres { get; set; }
        public DbSet<CaptureLowre> CaptureLowres { get; set; }        
        public DbSet<CurrentItem> CurrentItems { get; set; }
        public DbSet<FontDefine> FontDefines { get; set; }
        public DbSet<RecordHighre> RecordHighres { get; set; }        
        public DbSet<SubtitleStyle> SubtitleStyles { get; set; }       
    }
}
