//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayVideoInMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaptureLowre
    {
        public long CaptureId { get; set; }
        public int ChannelId { get; set; }
        public string ProgramName { get; set; }
        public string FileName { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int Status { get; set; }
        public string StatusMessage { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Channel Channel { get; set; }
    }
}
