//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayVideoInMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channel
    {
        public Channel()
        {
            this.CaptureLowres = new HashSet<CaptureLowre>();
            this.CurrentItems = new HashSet<CurrentItem>();
            this.FontDefines = new HashSet<FontDefine>();
            this.RecordHighres = new HashSet<RecordHighre>();
            this.RecordLowres = new HashSet<RecordLowre>();
            this.SubtitleCategories = new HashSet<SubtitleCategory>();
        }
    
        public int ChannelId { get; set; }
        public string ChannelName { get; set; }
        public int DelayExpected { get; set; }
        public int RealisticDelay { get; set; }
        public Nullable<int> StyleId { get; set; }
    
        public virtual ICollection<CaptureLowre> CaptureLowres { get; set; }
        public virtual ICollection<CurrentItem> CurrentItems { get; set; }
        public virtual ICollection<FontDefine> FontDefines { get; set; }
        public virtual ICollection<RecordHighre> RecordHighres { get; set; }
        public virtual ICollection<RecordLowre> RecordLowres { get; set; }
        public virtual ICollection<SubtitleCategory> SubtitleCategories { get; set; }
    }
}
