//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayVideoInMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FontDefine
    {
        public FontDefine()
        {
            this.SubtitleStyles = new HashSet<SubtitleStyle>();
        }
    
        public int FontId { get; set; }
        public int ChannelId { get; set; }
        public string FontName { get; set; }
        public string FontFile { get; set; }
    
        public virtual Channel Channel { get; set; }
        public virtual ICollection<SubtitleStyle> SubtitleStyles { get; set; }
    }
}
