//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayVideoInMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubtitleTimeLine
    {
        public long TimeLineId { get; set; }
        public int FileId { get; set; }
        public System.DateTime StartTime { get; set; }
    
        public virtual SubtitleFile SubtitleFile { get; set; }
    }
}
