//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayVideoInMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubtitleFileItem
    {
        public long ItemId { get; set; }
        public int FileId { get; set; }
        public long StartTime { get; set; }
        public int Duration { get; set; }
        public string Text { get; set; }
        public int Position { get; set; }
        public int Align { get; set; }
    
        public virtual SubtitleFile SubtitleFile { get; set; }
    }
}
