//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayVideoInMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubtitleFile
    {
        public SubtitleFile()
        {
            this.SubtitleFileItems = new HashSet<SubtitleFileItem>();
            this.SubtitleTimeLines = new HashSet<SubtitleTimeLine>();
        }
    
        public int FileId { get; set; }
        public string ProgramName { get; set; }
        public int CategoryId { get; set; }
    
        public virtual SubtitleCategory SubtitleCategory { get; set; }
        public virtual ICollection<SubtitleFileItem> SubtitleFileItems { get; set; }
        public virtual ICollection<SubtitleTimeLine> SubtitleTimeLines { get; set; }
    }
}
